- models/lstm_encdec.py
- tests/train_torch_deterministic.py
Changes included:
* updated the renamed `target_pos` variable
* updated the `remamed plot_traj` function to `plot_traj_img`
* set `x_last` in `predict` function since it was referenced before assignment.
> Get deterministic model working

- tests/test_directory_utils.py
- utils/constants.py
- utils/directory_utils.py
- utils/train_utils.py
Enable directory utils:
- function to create a directory and its parent, if does not exist.
> Enable directory utils

- tests/train_torch_deterministic_with_variances.py
- tests/train_torch_ensembles_calibration.py
- utils/calibration.py
Changes in PR include:
- Changed some ESP comments by ENG comments 
- Used `REFERENCE` constant instead of the hardcoded version of it.
- Used explicit name variables for model instantiation
- Fixed FileNotFoundError for `calibration.py`, turns out that sample trajectories where not properly saved due to a hardcoded path, now it's fixed and all the plots are properly generated and saved (see samples below)
> Small improvements to train scripts

- models/bayesian_models_gaussian_loss.py
- tests/train_torch_deterministic_gaussian.py
- tests/train_torch_dropout_calibration.py
- tests/train_torch_variational_calibration.py
- utils/datasets_utils.py
> Fixing broken tests

- utils/calibration.py
> Refactor on generate_one_batch_test function.

- utils/calibration.py
Changed hardcoded image output paths in Isotonic regression function.
Changed hardcoded image output paths in calibration conformal function.
> Changed hardcoded image output paths in Isotonic regression function.

- utils/calibration.py
> compute calibration metrics function added 

- utils/calibration.py
> Removed commented code from gaussian_kde2 function

- tests/train_torch_deterministic_with_variances.py
> Removed unused reference

- tests/test_calibration.py
- tests/train_torch_deterministic_gaussian.py
- utils/calibration_utils.py
- utils/constants.py
> Split calibration compute from deterministic gaussian test

- README.md
> Added steps to execute calibration script

- utils/calibration.py
> Renamed pdf_flag to be relative_coords_flag

- datasets/sdd/preprocess_sdd.py
> Added preprocessed SDD dataset computed by OpenTraj toolkit

- datasets/sdd/preprocess_sdd.py
- tests/train_torch_deterministic_gaussian_sdd.py
- utils/datasets_utils.py
> SDD interface

- tests/train_torch_deterministic_gaussian_sdd.py
- utils/datasets_utils.py
> Added compute_neighbors flag to datasets_utils

- tests/train_torch_deterministic_gaussian_sdd.py
> Added validation proportion parameter as user argument

- tests/train_torch_deterministic_gaussian_sdd.py
- utils/datasets_utils.py
> Added max_overlap parameter as user argument.

- datasets/sdd/preprocess_sdd.py
> Updatated SDD raw dataset

- tests/train_torch_deterministic_gaussian.py
- tests/train_torch_deterministic_gaussian_sdd.py
> Fixed directory not found

- tests/train_torch_deterministic_gaussian.py
- tests/train_torch_deterministic_gaussian_sdd.py
> Moved import util so it is visible to workspace

- tests/train_deterministic_gaussian_sdd.py
- utils/constants.py
> Fixed output name for sdd dataset

- tests/train_bitrap_BT_sdd.py
- tests/train_deterministic_gaussian.py
- tests/train_deterministic_gaussian_sdd.py
- tests/train_dropout.py
- tests/train_dropout_sdd.py
- tests/train_ensembles_sdd.py
- tests/train_variational.py
- tests/train_variational_sdd.py
> Added max-overlap parameter to tests for SDD dataset
